spring.application.name=guardian

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/guardian_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080
