spring.application.name=guardian

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/guardian_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080

jwt.secret=GuardianIdentityPlatformSecretKeyForJwtTokenGeneration2026
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jencysebasthiyar04@gmail.com
spring.mail.password=fbex glff vwxb lcqd

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
